version: '3.4'

services:
  sampleapidocker:
    image: ${DOCKER_REGISTRY-}sampleapidocker
    build:
      context: .
      dockerfile: SampleApiDocker/Dockerfile
    depends_on:
      - sampleapidocker.database
    ports:
      - "8080"
    links:
      - sampleapidocker.database

  sampleapidocker.database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sampleapidocker@123
    ports:
      - 1433:1433
    expose:
      - "1433"